# Generated by Django 4.0 on 2021-12-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('overview', models.TextField(blank=True)),
                ('grade', models.CharField(blank=True, choices=[('good', 'Good'), ('very good', 'Very Good'), ('excellent', 'Excellent')], max_length=50)),
                ('graduated_in', models.CharField(blank=True, max_length=4)),
                ('joined_in', models.CharField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('personal_picture', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('github', 'Github'), ('linkedin', 'Linkedin'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('google', 'Google'), ('dev', 'Dev'), ('hashnode', 'Hashnode'), ('stackoverflow', 'Stackoverflow'), ('medium', 'Medium'), ('youtube', 'Youtube'), ('pinterest', 'Pinterest')], max_length=50)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('link', models.URLField()),
            ],
        ),
    ]
